[package]
name = "rust-earth"
version = "0.0.1"
authors = ["kroisse@gmail.com"]

[lib]
name = "earth"
path = "src/lib.rs"

[dependencies.rust-xml]
git = "https://github.com/netvl/rust-xml.git"

[dependencies.http]
git = "https://github.com/chris-morgan/rust-http.git"

[dependencies.chrono]
git = "https://github.com/lifthrasiir/rust-chrono.git"
