[package]
name = "libearth-rust"
version = "0.0.1"
authors = ["kroisse@gmail.com"]

[lib]
name = "earth"
path = "src/lib.rs"

[dependencies.rust-xml]
git = "https://github.com/netvl/rust-xml.git"

[dependencies.http]
path = "../../rust-http"
# git = "https://github.com/chris-morgan/rust-http.git"
