[package]
name = "rust-earth"
version = "0.0.1"
authors = ["kroisse@gmail.com"]

[[lib]]
name = "earth"
path = "src/lib.rs"

[dependencies]
chrono = "*"
regex = "*"
regex_macros = "*"
time = "*"
url = "*"
xml-rs = "*"
